pipeline {
   agent none
   stages {
    stage('Back-end') {
        agent {
            docker { images 'maven:3.8.1-adoptopenjdk-11' }
            }
        steps {
            sh 'maven --version'
        }    
        }
    stage('Front-end') {
        agent {
            docker {  image 'node:16-alpine'}
            }
        steps {
            sh 'node --version'
        }    
        }
    }    
    }
   } 
}